### ISSUE TITLE
GNSINstaller: DataStoreType cannot be resolved to a type

### ISSUE THREAD

**Issue by crockct** [MobilityFirst/GNS#12]
I just pulled the most up-to-date version a few hours ago, and am trying to do a <a href="https://gns.name/wiki/index.php?title=Distributed_Install">distributed install</a> on Orbit (www.orbit-lab.org). When running the install, I get a Exception while uploading file:java.lang.NullPointerException. I suspect it is related to the error I see when examining my copy of the source code. I have a lot of errors in the GNSInstaller class, most importantly the following, shown from a screenshot of Eclipse.

In case you can't see the picture, the error in the GNSInstaller class that I'm getting is: **DataStoreType cannot be resolved to a type**

![datastore not resolved](https://cloud.githubusercontent.com/assets/5385069/15004772/36eb254a-1189-11e6-8f98-df0a4448a6e6.PNG)

**Comment by westyUMass** [comment]
This was a java compiler version issue. GNS requires Java 8.
